name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x', '18.x', '20.x', '22.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: npm ci
      - name: "Prettier"
        run: npm run lint:prettier
      - name: "ESLint"
        run: npm run lint:eslint
      - name: "Build"
        run: npm run build
      - name: "Test"
        run: npm run test
